stages:
  - build
  - deploy
  - cleanup

build:
  tags:
    - docker-runner
  stage: build
  script:
    - make build_container
    - make all
    - make archive
  artifacts:
    paths:
      - lessons.zip

deploy:
  tags:
    - docker-runner
  stage: deploy
  script:
    - curl -X POST -F token=$BLOG_TRIGGER -F ref=production "https://gitlab.ethz.ch/api/v4/projects/10623/trigger/pipeline"

cleanup:
  tags:
    - docker-runner
  stage: cleanup
  script:
    - make clean
  when: manual
